# Configuration
ENABLE_WRAPPER = False  # Set to True to enable experimental wrapper nodes
ENABLE_PIPE = True      # GPU Selector Pipe for device management

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

if ENABLE_PIPE:
    from .gpu_selector_pipe import NODE_CLASS_MAPPINGS as PIPE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PIPE_DISPLAY_MAPPINGS
    NODE_CLASS_MAPPINGS.update(PIPE_MAPPINGS)
    NODE_DISPLAY_NAME_MAPPINGS.update(PIPE_DISPLAY_MAPPINGS)

if ENABLE_WRAPPER:
    from .nodes import NODE_CLASS_MAPPINGS as WRAPPER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as WRAPPER_DISPLAY_MAPPINGS
    NODE_CLASS_MAPPINGS.update(WRAPPER_MAPPINGS)
    NODE_DISPLAY_NAME_MAPPINGS.update(WRAPPER_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']